### ISSUE TITLE
Incorrect test cases.

### ISSUE THREAD

**Issue by ChakshuGautam** [Konnect-Samagra/gql-utils#1]
Based on the baseQuery, [this](https://github.com/Konnect-Samagra/gql-utils/blob/4b14a7886e66c63385448bdae78866a2c28ea8b9/test/basic.test.ts#L21) doesn't seem like a valid query. `industry` should include either the same leaf node or a different leaf node.

**Comment by AnshulMalik** [comment]
https://github.com/Konnect-Samagra/gql-utils/commit/101285e8e5b772a04b0e1a4d00447f8dca147e12 fixes it.
